---
server:  
  port: ${PORT:8888}
---
spring:  
  application:
    name: config-server
  output:
    ansi:
      enabled: always 
---
logging:
  path: D:\logs\config.log
  pattern:
    level: INFO
---   
debug: false
---
spring:
  cloud:
    config:
      fail-fast: true
      server:
        git:
          uri: https://github.com/bipingupta/Microservices-Demo
          searchPaths: ConfigData
#          uri: file://D:/IBM/Workspace/SpringCloud/Microservices-Demo/ConfigData/Microservices-With-Spring-Student-Files
#          searchPaths: ConfigData
           
