---  
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.
---
spring:
  cloud:
    config:
      uri: http://${SERVER_IP:localhost}:8888
      fail-fast: true
      retry:
        max-attempts: 30
---
eureka:
  instance:
#   hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${SERVER_IP:localhost}:8761/eureka/
---
spring:
  output:
    ansi:
      enabled: always
---
logging:
  level:
    org.springframework.retry: trace
    com.netflix.discovery: trace
---
spring:
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
---
spring:
  sleuth:
    sampler:
      probability: 1
---
debug: true
---
words: fallback
---
spring:
  profiles: subject
  application:
    name: subject
logging:
  path: D:\logs\subject.log
  pattern:
    level: INFO
---
spring:
  profiles: verb
  application:
    name: verb
logging:
  path: D:\logs\verb.log
  pattern:
    level: INFO
---
spring:
  profiles: article
  application:
    name: article
logging:
  path: D:\logs\article.log
  pattern:
    level: INFO
---
spring:
  profiles: adjective
  application:
    name: adjective
logging:
  path: D:\logs\adjective.log
  pattern:
    level: INFO
---
spring:
  profiles: noun
  application:
    name: noun
logging:
  path: D:\logs\noun.log
  pattern:
    level: INFO