---
server:
  port: ${PORT:9191}
---
spring:
  application:
    name: oauth2server
  output:
    ansi:
      enabled: always
---
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${SERVER_IP:localhost}:8761/eureka/
---
logging:
  path: D:\logs\OAuth2.log
  level: 
     org.springframework.security: TRACE
---   
debug: false