---
server:  
  port: ${PORT:8765}
---
spring:  
  application:
    name: admin-server
  output:
    ansi:
      enabled: always
---
spring:
  security:
    user:
      name: admin
      password: admin
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 
         