---
server:  
  port: ${PORT:8020}
---
spring:  
  application:
    name: sentence
  output:
    ansi:
      enabled: always 
---
eureka:
#  instance:
#   hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${SERVER_IP:localhost}:8761/eureka/
---
spring:
  cloud:
    config:
      uri: http://${SERVER_IP:localhost}:8888
      fail-fast: true
      retry:
        max-attempts: 30
---
logging:
  level:
    org.springframework.retry: trace
    com.netflix.discovery: trace
---
debug: true
---
logging:
  path: D:\logs\sentence.log
  pattern:
    level: INFO
---
spring:
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
---
spring:
  sleuth:
    sampler:
      probability: 1
---
management:
  endpoints:
    web:
      exposure:
        include: 
        - hystrix.stream





