---
server:
  port: ${PORT:8761}
---
spring:  
  application:
    name: eureka-server
  output:
    ansi:
      enabled: always 
---    
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
logging:
  level:
    org.springframework.cloud.netflix.eureka: TRACE
---
debug: false
---      
logging:
  path: D:\logs\eureka.log
  pattern:
    level: INFO

      
 