###############################################################
### Default configuration for development environment.      ###
###############################################################
version: '2'
services:
  eureka:
    restart: always
    build: ./micro1-eureka-server
    ports:
      - "8761:8761"
  config:
    restart: always
    build: ./micro2-config-server
    ports:
      - "8888:8888"
    depends_on:
      - "eureka"
  subject:
    restart: always
    build: ./micro3-word-server
    ports:
      - "8081:8081"
    links:
      - eureka
      - config
    depends_on:
      - "eureka"
      - "config"
  verb:
    restart: always
    build: ./micro4-word-server
    ports:
      - "8082:8082"
    links:
      - eureka
      - config
    depends_on:
      - "eureka"
      - "config"
  article:
    restart: always
    build:  ./micro5-word-server
    ports:
      - "8083:8083"
    links:
      - eureka
      - config
    depends_on:
      - "eureka"
      - "config"
  adjective:
    restart: always
    build:  ./micro6-word-server
    ports:
      - "8084:8084"
    links:
      - eureka
      - config
    depends_on:
      - "eureka"
      - "config"
  noun:
    restart: always
    build: ./micro7-word-server
    ports:
      - "8085:8085"
    links:
      - eureka
      - config
    depends_on:
      - "eureka"
      - "config"
  sentence:
    restart: always
    build: ./micro9-sentence-server
    ports:
      - "8020:8020"
    links:
      - eureka
      - config
      - noun
      - adjective
      - article
      - verb
      - subject
    depends_on:
      - "eureka"
      - "config"
      - "noun"
      - "adjective"
      - "article"
      - "verb"
      - "subject"